theme: jekyll-theme-slate
title: Marcelle's Resources
author:
  name: Marcelle Lee
  email : marcellelee at protonmail.com
  github : marcellelee
  twitter : marcellelee
  feedburner : nil
description: Curated tips and tools
exclude: ["README.md", "Rakefile", "LICENSE.md"]

JB :
  version : 0.3.0
  archive_path: nil
  categories_path : nil
  tags_path : nil
  atom_path : nil
  rss_path : nil
  comments :
    provider : false
  analytics :
    provider : false
  sharing :
     provider : false
