theme: jekyll-theme-slate
title: Marcelle's Handy Dandy References!
description: # Marcelle's Mess

I done did got me ducks in a row.

## My Resources

All of these were written or developed by me, at least in part.

## Other Resources

Not my own work, but I learned from or regularly reference these.

## About Me

Love too Chardonnay

### Certifications
- Sec+
- CISSP
